deutsche-nationalbibliothek/pica-rs

.github/workflows/main.yml
Cargo.toml

Setup GitHub Actions

---

.github/workflows/ci.yml
.github/workflows/main.yml
README.md

Setup GitHub Pages

---

Cargo.toml
LICENSE
README.md

Use AGPL-3.0 license

---

Cargo.toml
src/lib.rs
src/parser.rs

Add Pica+ parser

---

.github/workflows/ci.yml

Run tests on rust beta and nightly

---

.github/workflows/ci.yml
.github/workflows/main.yml

Run cargo audit only on main branch

---

.github/actions-rs/grcov.yml
.github/workflows/ci.yml
.github/workflows/main.yml
README.md

Setup code coverage

---

.github/workflows/ci.yml
README.md
src/error.rs
src/lib.rs
src/record.rs

Implement `FromStr` trait for Record

---

Cargo.toml
README.md
src/bin/pica/main.rs
src/filter.rs
src/parser/filter.rs
src/record.rs

Add regex operator

---

src/filter.rs
src/parser/filter.rs
src/record.rs
tests/filter.rs

Add startswith and endswith operator

---

Cargo.toml
README.md
src/bin/pica/commands/common.rs

Support gzip compressed files

---

src/filter.rs
src/parser.rs
src/record.rs

Add Not-Operator

---

src/bin/pica/commands/cat.rs
src/bin/pica/commands/filter.rs
src/bin/pica/commands/json.rs
src/bin/pica/commands/print.rs
src/bin/pica/commands/sample.rs
src/bin/pica/commands/select.rs
src/field.rs
src/record.rs
src/subfield.rs
tests/field.rs
tests/filter.rs
tests/record.rs
tests/subfield.rs

Use copy-on-write smart pointers

---

.github/workflows/main.yml

Add cargo-outdated job to main workflow

---

.github/workflows/main.yml

Run main workflow daily

---

src/path.rs

Fix path parser on invalid indices values

---

src/field.rs
src/filter.rs

Add not operator

---

README.md
src/bin/pica/commands/mod.rs
src/bin/pica/commands/split.rs
src/bin/pica/main.rs

Add split command

---

README.md
src/bin/pica/commands/mod.rs
src/bin/pica/commands/partition.rs
src/bin/pica/main.rs

Add partition command

---

README.md
src/bin/pica/commands/invalid.rs
src/bin/pica/commands/mod.rs
src/bin/pica/main.rs

Add invalid command

---

README.md
src/bin/pica/commands/frequency.rs
src/bin/pica/commands/mod.rs
src/bin/pica/main.rs

Add frequency command

---

Cargo.toml
README.md
src/bin/pica/cli.rs
src/bin/pica/commands/cat.rs
src/bin/pica/commands/completion.rs
src/bin/pica/commands/filter.rs
src/bin/pica/commands/frequency.rs
src/bin/pica/commands/invalid.rs
src/bin/pica/commands/json.rs
src/bin/pica/commands/mod.rs
src/bin/pica/commands/partition.rs
src/bin/pica/commands/print.rs
src/bin/pica/commands/sample.rs
src/bin/pica/commands/select.rs
src/bin/pica/commands/split.rs
src/bin/pica/main.rs
src/bin/pica/util.rs

Add completion command

---

src/record.rs
src/select.rs

Add index syntax for subfields in selectors

---

README.md
src/field.rs
src/filter.rs

Add in operator

---

src/bin/pica/commands/partition.rs

Fix template parameter in partition command

---

README.md
src/field.rs
src/filter.rs

Add starts-with and ends-with operator

---

README.md
src/filter.rs
tests/test_filter_cmd.rs

Add field existence operator

---

src/filter.rs

Verify regex in filter expressions

---

.github/workflows/release.yml

Setup release workflow

---

README.md
src/bin/pica/cmds/select.rs
tests/test_select_cmd.rs

Add `--tsv` flag to use tab character as field delimiter

---

.github/workflows/release.yml
src/bin/pica/cmds/frequency.rs
tests/test_pica.rs

Fix `limit` parameter in `frequency` command

---

.github/workflows/release.yml
src/bin/pica/cmds/partition.rs

Flush writers before exit in `partition`command

---

src/bin/pica/cmds/frequency.rs
tests/test_pica.rs

Add `threshold` parameter to `frequency` command

---

src/bin/pica/cmds/json.rs
src/bin/pica/cmds/mod.rs
src/bin/pica/main.rs
src/record.rs
tests/test_pica.rs

Implement serializer for `StringRecord`

---

src/bin/pica/main.rs

Handle broken pipes properly

---

src/bin/pica/cmds/select.rs
tests/test_pica.rs

Add `--header` parameter to `select` command

---

README.md
src/filter.rs
tests/test_pica.rs

Add `not in` operator

---

src/bin/pica/cmds/filter.rs
tests/test_pica.rs

Add `limit` parameter to `filter` command

---

src/bin/pica/cmds/filter.rs
src/bin/pica/cmds/print.rs
src/reader.rs
tests/test_pica.rs

Add `limit` parameter to `print` command

---

src/bin/pica/cmds/frequency.rs
tests/test_pica.rs

Add `reverse` flag to `frequency` command

---

tests/pica/partition.rs

Handle invalid path expression properly

---

src/bin/pica/cmds/split.rs
tests/pica/split.rs

Handle invalid chunk size properly

---

src/bin/pica/cmds/slice.rs
tests/pica/slice.rs

Handle invalid slice options properly

---

src/bin/pica/cmds/filter.rs
src/filter.rs
tests/pica/filter.rs

Add test to handle invalid regex in filter expressions

---

src/bin/pica/cmds/frequency.rs
tests/pica/frequency.rs

Fix `threshold` option in `frequency` command

---

tests/pica/split.rs

Fix `split_default` integration test

---

LICENSE
README.md
UNLICENSE

Add license information

---

.github/workflows/main.yml
Cargo.toml

Replace `cargo-outdated` by `cargo-upgrades`

---

src/path.rs

Fix unresolved links in documentation

---

src/filter.rs
tests/pica/filter.rs

Allow filter to start and end with whitespaces

---

README.md
src/record.rs
src/select.rs
tests/pica/select.rs

Add static values in select expressions

---

src/filter.rs
tests/pica/filter.rs
tests/pica/select.rs

Add occurrence ranges

---

.github/workflows/ci.yml
fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_byte_record.rs
fuzz/fuzz_targets/fuzz_filter.rs
fuzz/fuzz_targets/fuzz_path.rs
fuzz/fuzz_targets/fuzz_selectors.rs

Add fuzz testing

---

README.md

Add deps.rs status badge

---

src/bin/pica/cmds/select.rs
tests/pica/select.rs

Add `--no-empty-columns` flag to `select` command

---

Cargo.toml
src/bin/pica/cmds/print.rs
src/bin/pica/main.rs
src/record.rs
tests/data/1004916019-color.txt
tests/data/1004916019-spaces.txt
tests/data/1004916019.txt
tests/data/dump.txt
tests/pica/print.rs

Use `Pica Plain` format in `print` command

---

.github/workflows/ci.yml

This reverts commit 2772d3e812cc64800fbe22c7769e396fa168e3d4.

Revert "Disable broken cargo-fuzz (#300)"

---

src/bin/gnd2skos/cli.rs
src/bin/gnd2skos/main.rs
src/bin/pica/cmds/filter.rs
src/bin/pica/cmds/select.rs
src/filter.rs
src/record.rs
tests/pica/filter.rs
tests/pica/select.rs

Add `--case-ignore` flag to `filter` and `select` command

---

README.md
docs/book/src/de/referenz/matcher.md
src/matcher.rs
tests/pica/filter.rs

Add cardinality operator

---

docs/book/src/de/referenz/subfield.md
src/matcher.rs
tests/pica/filter.rs

Add a wildcard character for all subfield codes

---

Cargo.toml
docs/book/src/de/referenz/matcher.md
src/bin/gnd2skos/main.rs
src/bin/pica/cmds/filter.rs
src/matcher.rs
src/record.rs
tests/pica/filter.rs

Add string similarity operators

---

tests/pica/partition.rs

Fix partition template unit test on OS X

---

README.md

Marked as unstable because of
<https://github.com/deutsche-nationalbibliothek/pica-rs/issues/249>.

List `json` command in README

---

src/bin/pica/cmds/frequency.rs
tests/pica/frequency.rs

- [Unicode Character “ä” (U+00E4)](https://www.compart.com/en/unicode/U+00E4), UTF8-Encoding: 0xC3 0xA4, Decomposed: [a (U+0061)](https://www.compart.com/en/unicode/U+0061) - [◌̈ (U+0308)](https://www.compart.com/en/unicode/U+0308)
- [Unicode Character “a” (U+0061)](https://www.compart.com/en/unicode/U+0061), UTF8-Encoding: 0x61
- [Unicode Character “◌̈” (U+0308)](https://www.compart.com/en/unicode/U+0308), UTF8-Encoding: 0xCC 0x88
```bash
$ pica filter --reduce "029A" "003@.0?" tests/data/004732650.dat.gz  | \
pica frequency "029A." | hexdump -C
00000000  47 6f 65 74 68 65 2d 55  6e 69 76 65 72 73 69 74  |Goethe-Universit|
00000010  61 cc 88 74 20 46 72 61  6e 6b 66 75 72 74 20 61  |a..t Frankfurt a|
00000020  6d 20 4d 61 69 6e 2c 31  0a                       |m Main,1.|
```
```bash
$ …
```

Add `--translit` option to `frequency` command

---

docs/book/src/de/SUMMARY.md
docs/book/src/de/guide/cmds/completions.md

Preview:
https://github.com/deutsche-nationalbibliothek/pica-rs/blob/completion-docs/docs/book/src/de/guide/cmds/completions.md
Review:
https://github.com/deutsche-nationalbibliothek/pica-rs/pull/415/files#diff-47f7c96f26d88422044266b954d3806b1cc2e668ef283e18338534f8921d16cc

Document `completions` command

---

README.md
docs/book/src/de/SUMMARY.md
docs/book/src/de/guide/cmds/count.md

Preview:
https://github.com/deutsche-nationalbibliothek/pica-rs/blob/count-docs/docs/book/src/de/guide/cmds/count.md
Review:
https://github.com/deutsche-nationalbibliothek/pica-rs/pull/420/files#diff-953ba317a4a823cc9bb2b0e62f4094f2c04e01da7749a7992d0b47333d5f2dd7

Document `count` command

---

docs/book/src/de/SUMMARY.md
docs/book/src/de/guide/cmds/frequency.md

Preview:
https://github.com/deutsche-nationalbibliothek/pica-rs/blob/freq-docs/docs/book/src/de/guide/cmds/frequency.md
Review:
https://github.com/deutsche-nationalbibliothek/pica-rs/pull/423/files#diff-0f9b0ca14800500a051ddc473400b3c9ba319f51e08d309d9203e76874078918

Document `frequency` command

---

src/bin/pica/cmds/filter.rs
tests/pica/filter.rs

Allow spaces in `--reduce` option

---

src/matcher/subfield_list_matcher.rs
tests/pica/filter.rs

Fix parsing of boolean conntected filter expr

---

.github/workflows/ci.yml
Cross.toml

CI workflow improvements
- better caching (fix wrong cache-keys)
- use cross compilation (builds on CentOS)
- run jobs for workspace memebers
- faster workflow for drafts

Refactor continuous integration workflow

---

docs/book/src/de/SUMMARY.md
docs/book/src/de/guide/cmds/invalid.md

Preview:
https://github.com/deutsche-nationalbibliothek/pica-rs/blob/invalid-docs/docs/book/src/de/guide/cmds/invalid.md
Review:
https://github.com/deutsche-nationalbibliothek/pica-rs/pull/500/files#diff-3ee16f6744575b31866d8fae3ca50fb086dca67790bb17b803973a2d12c84e86

Document `invalid` command

---

Cargo.toml
README.md
docs/book/src/de/guide/installation.md
pica-record/CHANGELOG.md

This reverts commit 51ffc577815f5f88f0312752333b0d08208b5b2c.

Revert "Release version 0.13.0 (#501)"

---

CHANGELOG.md
README.md
docs/book/src/de/guide/cmds/cat.md

Stabilize `cat` command

---

CITATION.cff

This adds a CITATION.CFF. Methods to automatically update version and date-released are not included yet.

Add citation information

---

README.md

Extend documentation of `filter` command

---

CITATION.cff
Cargo.toml
README.md
docs/book/src/de/guide/installation.md

Release version 0.15.1

---

src/bin/pica/commands/cat.rs
tests/snapshot/cat/016-cat-unique-idn.toml
tests/snapshot/cat/017-cat-unique-hash.toml
tests/snapshot/cat/018-cat-unique-no-idn.toml

Concatenate records without duplicates

---

docs/book/src/SUMMARY.md
docs/book/src/referenz/kommandos/convert.md
docs/book/src/referenz/kommandos/index.md

Preview: https://github.com/deutsche-nationalbibliothek/pica-rs/blob/convert-docs/docs/book/src/referenz/kommandos/convert.md
Review: https://github.com/deutsche-nationalbibliothek/pica-rs/pull/661/files#diff-2a2d11527458dc72175b4766ed9c9c635b31daf537d0d8eab945feed56a8bdb0

Add `convert` documentation

---

docs/book/src/SUMMARY.md
docs/book/src/referenz/kommandos/index.md
docs/book/src/referenz/kommandos/print.md
pica-toolkit/tests/snapshot.rs

- [Preview](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/add-print-docs/docs/book/src/referenz/kommandos/print.md)
- [Review](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/668/files#diff-97381c3a71be2ced31303fdfcfa9eea333b5a6fee877e179e3aa6539e3daee33)

Add `print` documentation

---

CHANGELOG.md
README.md
pica-matcher/src/common.rs
pica-matcher/src/subfield_matcher.rs
pica-matcher/tests/subfield_matcher.rs
pica-toolkit/tests/snapshot/filter/0114-filter-relation-matcher-curly-contains-f.toml
pica-toolkit/tests/snapshot/filter/0114-filter-relation-matcher-curly-contains-t.toml
pica-toolkit/tests/snapshot/filter/0114-filter-relation-matcher-simple-contains-f.toml
pica-toolkit/tests/snapshot/filter/0114-filter-relation-matcher-simple-contains-t.toml

This PR adds the new  `=?` operator to check if the given value is a substring.

Add contains relation matcher (`=?`)

---

CHANGELOG.md
CITATION.cff
Cargo.toml
README.md
docs/book/src/anleitungen/installation.md

Release version 0.19.0

---

CHANGELOG.md
CITATION.cff
Cargo.toml
README.md
docs/book/src/anleitungen/installation.md

Release version 0.20.0

---

Cargo.toml
pica-cli/Cargo.toml

build(deps): bump `polars` to `0.45`

---

src/query.rs

Fix incorrect use of empty format outcome
