tests/pica/split.rs
The `split_default` integration tests panics sporadically, because of parallel execution. If the `--test-threads` option is set to `1` everything is fine. Instead of disable the parallel execution, the test is removed because the `split_outdir` test covers the same functionality.
Closes #224
=> Remove `split_default` integration tests

tests/pica/split.rs
Since Rust 1.53.0 arrays implement the `IntoIterator` trait and explicitly calling `iter()` is unnecessary.
=> Remove unnecessary `iter()` call

README.md
The print command uses a custom format similar to PICA Plain with additional space after each subfield code. I guess that `$` in a subfield value is not escaped as `$$` like it is in PICA Plain.
=> README: PICA3 => PICA Plain

src/bin/pica/cmds/select.rs, tests/pica/select.rs
When the `--unique`/`-u` flag is set, duplicate rows will be skipped.
**Example**
```shell
$ pica select "003@.0,028[A@].d" tests/data/121169502.dat
121169502,Heike
121169502,Heike
$ pica select --unique "003@.0,028[A@].d" tests/data/121169502.dat
121169502,Heike
```
Closes #347
=> Add `--unique` flag

Cargo.toml, README.md, src/bin/pica/cmds/mod.rs, src/bin/pica/cmds/print.rs, src/bin/pica/cmds/xml.rs, src/bin/pica/config.rs, src/bin/pica/main.rs, src/bin/pica/util.rs, src/field.rs, src/occurrence.rs, tests/data/1004916019.xml, tests/data/dump.xml, tests/data/invalid.xml, tests/pica/mod.rs, tests/pica/xml.rs
This change adds a new command to serialize PICA+ records to [PICA XML](https://verbundwiki.gbv.de/display/VZG/PICA+XML+Version+1.0).
The command 
```shell
$ pica xml --skip-invalid tests/data/1004916019.dat
```
produces the following XMl document:
```xml
<?xml version="1.0" encoding="utf-8"?>
<collection xmlns="info:srw/schema/5/picaXML-v1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="info:srw/schema/5/picaXML-v1.0">
<record>
<datafield tag="001A">
<subfield code="0">8999:22-07-10</subfield>
</datafield>
<datafield tag="001B">
<subfield code="0">1250:10-09-14</subfield>
<subfield code="t">08:28:16.000</subfield>
</datafield>
<datafield tag="001D">
<subfield code="0">0384:27-07-10</subfield>
</datafield>
<datafield tag="001U">
<subfield code="0">utf8</subfield> …
```
=> Add `xml` command

.github/workflows/ci.yml
This PR adds a new test which checks for unused dependencies in `Cargo.toml` using [cargo-udeps](https://github.com/est31/cargo-udeps).
=> Add check for unused dependencies in `Cargo.toml`

src/matcher/record_matcher.rs
This PR fix record matcher expressions starting with a `Not` expression combined with a boolean operator. Until now the following expressions failed:
```bash
$ pica filter "!012A? && ..."
```
=> Fix `RecordMatcher` parser

src/bin/pica/cmds/xml.rs, tests/data/004732650-nfc.xml, tests/data/004732650-nfd.xml, tests/pica/xml.rs
- [Unicode Character “ä” (U+00E4)](https://www.compart.com/en/unicode/U+00E4), UTF8-Encoding: 0xC3 0xA4, Decomposed: [a (U+0061)](https://www.compart.com/en/unicode/U+0061) - [◌̈ (U+0308)](https://www.compart.com/en/unicode/U+0308)
- [Unicode Character “a” (U+0061)](https://www.compart.com/en/unicode/U+0061), UTF8-Encoding: 0x61
- [Unicode Character “◌̈” (U+0308)](https://www.compart.com/en/unicode/U+0308), UTF8-Encoding: 0xCC 0x88
```bash
$ pica filter --reduce "029A" "003@.0?" tests/data/004732650.dat.gz  | \
pica xml | hexdump -C
00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 75 74  |.0" encoding="ut|
00000020  66 2d 38 22 3f 3e 0a 3c  63 6f 6c 6c 65 63 74 69  |f-8"?>.<collecti|
00000030  6f 6e 20 78 …
```
=> Add `--translit` option to `xml` command

src/bin/pica/cmds/print.rs, src/bin/pica/main.rs, src/bin/pica/translit.rs, tests/data/004732650-nfc.txt, tests/data/004732650-nfd.txt, tests/pica/print.rs
- [Unicode Character “ä” (U+00E4)](https://www.compart.com/en/unicode/U+00E4), UTF8-Encoding: 0xC3 0xA4, Decomposed: [a (U+0061)](https://www.compart.com/en/unicode/U+0061) - [◌̈ (U+0308)](https://www.compart.com/en/unicode/U+0308)
- [Unicode Character “a” (U+0061)](https://www.compart.com/en/unicode/U+0061), UTF8-Encoding: 0x61
- [Unicode Character “◌̈” (U+0308)](https://www.compart.com/en/unicode/U+0308), UTF8-Encoding: 0xCC 0x88
```bash
$ pica filter --reduce "029A" "003@.0?" tests/data/004732650.dat.gz  | \
pica print | hexdump -C
00000000  30 32 39 41 20 24 61 47  6f 65 74 68 65 2d 55 6e  |029A $aGoethe-Un|
00000010  69 76 65 72 73 69 74 61  cc 88 74 20 46 72 61 6e  |iversita..t Fran|
00000020  6b 66 75 72 74 20 61 6d  20 4d 61 69 6e 24 62 49  |kfurt am Main$bI|
00000030  6e 73 74 69 …
```
=> Add `--translit` option to `print` command

src/bin/pica/cmds/cat.rs, tests/pica/cat.rs
With this change, the `cat` command can read form standard input (`stdin`). This is usefull when the output of an other process must be concatenated with one or multiple files. When no filenames are given as arguments or a filename is equal to `-`, the commands reads from `stdin`.
```bash
$ pica filter -s "003@.0 == '0123456789X'" | pica cat - file1.dat file2.dat.gz file3.dat -o result.dat
```
=> Allow `cat` command to read from `stdin`

src/bin/pica/cmds/cat.rs, tests/pica/cat.rs
This change adds the `--tee` option to the `cat` command. This options acts like the linux `tee` command. If this option is set, the output of the `cat` command will be written to a file (`tee`'s value) and to the standard output (`stdout`). This feature is usefull when the output is needed by a next command (separate call) *and* the output is processed by a other command (in a pipeline).
The option `--tee` cannot be used with `--output`.
```bash
$ pica cat --skip-invalid --tee gnd.dat partitions/T*.dat | pica filter "002@.0 =^ 'Ts'" \
--output gnd_subject_terms.dat
$ pica filter "002@.0 =^ 'Tp'" gnd.dat -o gnd_persons.dat
```
=> Add `--tee` option to `cat` command

src/bin/pica/cmds/cat.rs, src/writer.rs, tests/pica/cat.rs
This change adds the `--append` option to the `cat` command. If this flag is set, the output will be appended to the file (if exists), otherwise the file will be crated. The flag is disabled by default and must be set explicitly. The behaviour of the `--output` value as well as the `--tee` value is affected by this flag.
The flag has no effect when writing to standard output (`stdout`).
```bash
$ pica cat partitions/Ts*.dat -o A.dat
$ pica cat partitions/Tp*.dat --append -o A.dat # A.dat contains all records from Ts*.dat and Tp*.dat
```
=> Add `--append` option to `cat` command

README.md, docs/book/src/de/SUMMARY.md, src/bin/pica/cmds/completions.rs, src/bin/pica/cmds/mod.rs, src/bin/pica/main.rs, tests/pica/completions.rs, tests/pica/mod.rs
This PR changes the name of the `completion` command to `completions`, which is used more often.
=> Rename `completion` command to `completions`

src/bin/pica/cmds/count.rs, tests/data/dump_cnt.csv, tests/data/dump_cnt.tsv, tests/data/dump_cnt.txt, tests/data/invalid_cnt.txt, tests/pica/count.rs
This PR changes the output format of the `count` command:
- in text output a colon is append to the label
- in csv/tsv-output the rows and columns are transposed
- With the `--no-header` flag no header will be written
```bash
$ pica count -s tests/data/dump.dat.gz
records: 7
fields: 247
subfields: 549
```
```bash
$ pica count -s --csv tests/data/dump.dat.gz
records,fields,subfields
7,247,549
```
```bash
$ pica count -s --csv --no-header tests/data/dump.dat.gz
7,247,549
```
=> Change output format of `count` command

src/bin/pica/cmds/count.rs, tests/pica/count.rs
This change adds the flags `--records`, `--fields` and `--subfields`. If one of these flags is set, only the requested value will be printed on the terminal. These flags are mutual exclusive, setting more than one of these flags will result in an error. Also, the combination with the flags `--no-header`, `--csv` or `--tsv` is not allowed.
```bash
$ pica count -s --records tests/data/dump.dat.gz
7
$ pica count -s --fields tests/data/dump.dat.gz
247
$ pica count -s --subfields tests/data/dump.dat.gz
549
```
=> Allow `count` command to print single values

src/bin/pica/cmds/frequency.rs, tests/pica/frequency.rs
Until now, it was not possible to read from multiple input files. With this change, the `frequency` comands can read from multiple files. If no filename is present, or a filename is equal to `-`, the commands reads from standard input (`stdin`).
```bash
$ pica frequency -s "002@.0" file1.dat file2.dat.gz # read from multiple files
$ pica cat -s file.dat file2.dat.gz | pica frequency "002@.0" # read from stdin
$ pica cat -s file.dat | pica frequency -s "002@.0" - file2.dat.gz # read from stdin and file
```
=> Allow `frequency` command to read from multiple files

src/bin/pica/cmds/count.rs, src/writer.rs, tests/pica/print.rs
This PR fix a bug when a command writes to an existing file. Now, the output file is truncated to 0 length if the file already exists (in non-append mode).
Closes #438
=> Fix write to existing files

src/matcher/field_matcher.rs, src/matcher/record_matcher.rs, tests/pica/filter.rs
This change fixes parsing of filter expressions, which are connected with a boolean AND operator. The following (vaild) expression failed, due to an error in the parser.
```bash
$ pica filter -s "(003@.0?) && 002@.0 == 'Tp'"
```
Closes #443
=> Fix parsing of and-connected filter expressions

src/bin/pica/cmds/filter.rs, tests/pica/filter.rs
This pull requests adds the `--or` option to the `filter` command. This options is similar to the `--and` option and can be used to split a long filter expression into multiple parts. These parts are connected with the boolean `OR` operator. This can't be used in combination with the `--and` option. This option is especially useful when building the super-set of multiple sub-filters (filter A `or` filter B `or` filter C ...).
```bash
$ pica filter "002@.0 =^ 'Tp'" --or "002@ =^ 'Ts'" --or "002@.0 =^ 'Tc'" DUMP.dat.gz
```
=> Add `--or` option to `filter` command

src/bin/pica/cmds/filter.rs, src/matcher/record_matcher.rs, tests/pica/filter.rs
This pull request adds the `--not` option to the `filter` command. This option is similar to `--and` and can be used to split a long filter expression into multiple parts. These parts are connected with the boolean `AND` operator and the expression of the not-part is negated. This can't be used in combination with the `--or` option.
```bash
$ pica filter "002@.0 =^ 'T'" --and "002@ =$ '1'" --not "002@.0 == 'Tp1'" DUMP.dat.gz
```
=> Add `--not` option to `filter` command

src/bin/pica/cmds/filter.rs, tests/pica/filter.rs
This change adds the `--tee` option to the `filter` command. This option acts like the linux `tee` command. If this option is set, the output of the `filter` command will be written to a file (`tee`'s value) and to the standard output (`stdout`). This feature is usefull when the output is needed by a next command (separate call) *and* the output is processed by a other command (in a pipeline).
The option `--tee` cannot be used in combination with `--output`.
```bash
$ pica filter -s --tee gnd.dat "002@.0 =^ 'T'" | pica filter "002@.0 =^ 'Ts'" -o gnd_subject_terms.dat
```
=> Add `--tee` option to `filter` command

src/bin/pica/cmds/filter.rs, tests/pica/filter.rs
This change adds the `--append` option to the `filter` command. If this flag is set, the output will be appended to the file (if exists), otherwise the file will be crated. The flag is disabled by default and must be set explicitly. The behaviour of the `--output` value as well as the `--tee` value is affected by this flag.
The flag has no effect when writing to standard output (`stdout`).
```bash
$ pica filter "002@.0 == 'Ts1'" DUMP.dat.gz -o gnd.dat
$ pica filter --append "002@.0 == 'Tp1'" DUMP.dat.gz -o gnd.dat
$ pica filter --append "002@.0 == 'Tpz'" DUMP.dat.gz -o gnd.dat
```
=> Add `--append` option to `filter` command

src/bin/pica/cmds/filter.rs, tests/pica/filter.rs
The change introduce the short version of the `--allow-list` (`-A`) and `--deny-list` (`-D`) options of the `filter` command. Now, the following commands are equivalent:
```bash
$ pica filter --allow-list ALLOW.csv --deny-list DENY.csv "003@?" DUMP.dat.gz
$ pica filter -A ALLOW.csv -D DENY.csv "003@?" DUMP.dat.gz
```
=> Add short option for allow- and deny-lists

src/bin/pica/cmds/select.rs, tests/pica/select.rs
With this change it is now possible to filter records in a `select` command. Until now, it was necessary to use a combination of the `filter` and  `select` command in order to get data from a subset of records. Now, the `select` command provides the `--where` option, which accepts a pica filter expression.
The following comamnds are equivalent:
```bash
$ pica filter -s "003@.0 =^ '0'" DUMP.dat.gz | pica select "003@.0" -o idn.csv
$ pica select -s "003@.0" --where "003@.0 =^ '0'" DUMP.dat.gz  -o idn.csv
```
=> Allow filter expresions in `select` command

src/bin/pica/commands/select.rs, tests/pica/select.rs
This change adds the `--append` option to the `select` command. If this flag is set, the output will be appended to the file (if exists), otherwise the file will be crated. The flag is disabled by default and must be set explicitly.
The flag has no effect when writing to standard output (`stdout`).
```bash
$ pica select "003@.0, 002@.0" tests/data/1004916019.dat.gz -o out.csv
$ pica select "003@.0, 002@.0" tests/data/119232022.dat.gz --append -o out.csv
$ cat out.csv
1004916019,Ts1
119232022,Tp1
```
=> Add `--append` option to `select` command

Cargo.toml, src/bin/pica/commands/invalid.rs
This change improves the performance of the `invalid` command. The performance gain is achieved by using the new `pica-record` crate, which avoids as much unnecessary memory allocations as possible.
The benchmark uses an uncompressed dump of 37,238,584 records (47GB) with 15 invalid records. The measurements were made using hypefine with the following parameters:
```bash
$ hyperfine --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' --export-markdown invalid.md \
-L binary ${CARGO_BIN}/pica,${PROJECT_BIN}/pica '{binary} invalid DUMP.dat -o invalid.dat'
```
```bash
$ rustc -V
rustc 1.64.0 (a55dd71d5 2022-09-19)
```
| Revision | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `main` (`3564264`) | 797.436 ± 1.703 | 795.114 | 800.616 | 2.92 ± 0.01 |
| `HEAD` …
=> Improve `invalid` performance

Cargo.toml, pica-matcher/CHANGELOG.md, pica-matcher/Cargo.toml, pica-matcher/src/error.rs, pica-matcher/src/lib.rs, pica-matcher/src/tag_matcher.rs, pica-record/src/field.rs, pica-record/src/record.rs, pica-record/src/subfield.rs, pica-record/src/tag.rs
This is basically an improved and clean re-implementation of the existing tag matcher working on the new PICA primitives of the `pica-record` crate, except that the new one accepts range expressions inside a character class (ex. `0[13-59]2A`).
=> Add `TagMatcher` matcher

.github/workflows/ci.yml, pica-path/CHANGELOG.md, pica-path/src/lib.rs
Fix clippy warning:
```bash
error: using `.iter().next()` on an array
Error:    --> pica-path/src/lib.rs:132:9
|
132 |         self.path(&Path::new("003@.0")).iter().next().copied()
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try calling: `self.path(&Path::new("003@.0")).first()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#iter_next_slice
= note: `-D clippy::iter-next-slice` implied by `-D warnings`
error: could not compile `pica-path` due to previous error
Error: warning: build failed, waiting for other jobs to finish...
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```
=> Use `first()` instead of `iter().next()`

.github/actions-rs/package.yaml, .github/workflows/release.yml
This should work to fix #574 but I have not tested generation of packages with this GitHub workflow.
=> Include CLI completion files in packages

pica-matcher/src/field_matcher.rs, tests/snapshot/filter/0110-filter-not-field-curly-bracket-f.stdin, tests/snapshot/filter/0110-filter-not-field-curly-bracket-f.toml, tests/snapshot/filter/0110-filter-not-field-curly-bracket-t.stdin, tests/snapshot/filter/0110-filter-not-field-curly-bracket-t.stdout, tests/snapshot/filter/0110-filter-not-field-curly-bracket-t.toml
This PR reintroduce the negation of a field matcher in curly bracket notation. Example:
```bash
$ pica filter -s "!044H{ b == 'GND && 9? }" DUMP.dat.gz
```
=> Allow negation of a field matcher in curly bracket notation

pica-matcher/CHANGELOG.md, pica-matcher/src/common.rs, tests/snapshot/filter/0300-filter-double-quotes.stdin, tests/snapshot/filter/0300-filter-double-quotes.stdout, tests/snapshot/filter/0300-filter-double-quotes.toml
This PR adds support of double quoted string literals in a matcher expressions. The following two commands are equivalent:
```bash
$ pica filter '003@.0? && !041A.0?' DUMP.dat
$ pica filter "003@.0? && \!041A.0?" DUMP.dat
```
=> Support of double quoted string literals

src/bin/pica/commands/filter.rs, tests/snapshot/filter/0207-filter-limit.toml
This PR fixes a bug in `filter` command using the `limit` option. The bug only exists if more than one file is processed and the limit is less than the number of valid records (of all files). If the limit was reached the code stopped processing the current file, but continued with the remaining files. For each remaining file, up to one (valid) record was written to the output.
=> Fix `limit` in `filter` command

CHANGELOG.md, pica-record/src/io/mod.rs, pica-record/src/io/reader.rs, src/bin/pica/commands/invalid.rs, src/bin/pica/util.rs
This PR print a more helpful error messages if a input line is invalid and can't be decoded as PICA+. 
```
$ pica filter "003@?" tests/data/invalid.dat
Parse Pica Error: invalid record in line 0 (tests/data/invalid.dat)
$ pica filter "003@?" tests/data/dump.dat.gz
Parse Pica Error: invalid record in line 1 (tests/data/dump.dat.gz)
$ echo -e "003@ \x1f0123456789X\x1e\nfoobar\x1e" | pica print
003@ $0 123456789X
Parse Pica Error: invalid record in line 1 (stdin)
$ echo -e "003@ \x1f0123456789X\x1e" | cargo run -- print - tests/data/invalid.dat
003@ $0 123456789X
Parse Pica Error: invalid record in line 0 (tests/data/invalid.dat)
```
=> Print more helpful error message on `ParsePicaError`

CHANGELOG.md, README.md, pica-matcher/src/common.rs, pica-matcher/src/subfield_matcher.rs, tests/snapshot/filter/0113-filter-relation-matcher-curly-starts-not-with-f.stdin, tests/snapshot/filter/0113-filter-relation-matcher-curly-starts-not-with-f.toml, tests/snapshot/filter/0113-filter-relation-matcher-curly-starts-not-with-t.stdin, tests/snapshot/filter/0113-filter-relation-matcher-curly-starts-not-with-t.stdout, tests/snapshot/filter/0113-filter-relation-matcher-curly-starts-not-with-t.toml, tests/snapshot/filter/0113-filter-relation-matcher-simple-starts-not-with-f.stdin, tests/snapshot/filter/0113-filter-relation-matcher-simple-starts-not-with-f.toml, tests/snapshot/filter/0113-filter-relation-matcher-simple-starts-not-with-t.stdin, tests/snapshot/filter/0113-filter-relation-matcher-simple-starts-not-with-t.stdout, tests/snapshot/filter/0113-filter-relation-matcher-simple-starts-not-with-t.toml
This PR adds the _starts-not-with_ (`!^`) and the _ends-not-with_ (`!$`) relational operator. The `!^`-operator tests whether a  value starts *not* with the given prefix; and the `!$`-operator tests whether a value doesn't end with a given suffix.
```bash
$ pica filter '002@.0 !^ "T"' DUMP.dat.gz -o not-T.dat.gz
$ pica filter '002@{ 0 !$ "1" && 0 !$ "z" }' DUMP.dat.gz -o not-level-1z.dat.gz
```
=> Add `!^` and `!$` operator

docs/book/custom.css, docs/book/src/README.md, docs/book/src/SUMMARY.md, docs/book/src/referenz/kommandos/index.md
Vorschau: https://github.com/deutsche-nationalbibliothek/pica-rs/blob/docs-intro/docs/book/src/README.md
Review: https://github.com/deutsche-nationalbibliothek/pica-rs/pull/660/files#diff-a7abfd8d2b641f43f136f33cb55ec313aea94277aacef3f5440b906945ce86bf
=> Add project introduction

docs/book/src/SUMMARY.md, docs/book/src/referenz/kommandos/completions.md, docs/book/src/referenz/kommandos/index.md
* [Vorschau](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/revise-completion-docs/docs/book/src/referenz/kommandos/completions.md)
* [Review](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/662/files#diff-10c4e073bb27c86e5fd5e94633ca099305978a3db7975270e56a5b08158f6834)
=> Revise `completions` docs

pica-toolkit/src/commands/select.rs, pica-toolkit/tests/snapshot/select/047-select-squash-merge.toml
This PR required `--merge` and `--squash` to be mutually exclusive.
=> Require `--squash` and `--merge` to be mutually exclusive

docs/book/src/SUMMARY.md, docs/book/src/referenz/kommandos/hash.md, docs/book/src/referenz/kommandos/index.md, pica-toolkit/tests/snapshot.rs
* [Preview](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/add-hash-docs/docs/book/src/referenz/kommandos/hash.md)
* [Review](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/667/files#diff-8078730dab3830e6d4402dca9ad5d361efaf337cd38eecfb1ea2613587ff0f6e)
=> Add `hash` documentation

docs/book/src/README.md, docs/book/src/SUMMARY.md, docs/book/src/referenz/kommandos/cat.md, docs/book/src/referenz/kommandos/index.md, docs/book/src/referenz/kommandos/split.md, pica-toolkit/tests/snapshot.rs
-  [Preview](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/add-split-doc/docs/book/src/referenz/kommandos/split.md)
- [Review](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/670/files#diff-665a6555663687eb749667d0e2e359988fdd1b38cba56d3775c68b8846c65eae)
=> Add `split` documentation

docs/book/src/SUMMARY.md, docs/book/src/referenz/kommandos/index.md, docs/book/src/referenz/kommandos/slice.md, pica-toolkit/tests/snapshot.rs
- [Preview](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/add-slice-doc/docs/book/src/referenz/kommandos/slice.md)
- [Review](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/672/files#diff-385f62ec46cb0f004b3d6fdc42f91ff51c00556f076d4ddb541950ed15ad9076)
=> Add `slice` documentation

docs/book/src/SUMMARY.md, docs/book/src/referenz/kommandos/cat.md, docs/book/src/referenz/kommandos/filter.md, docs/book/src/referenz/kommandos/index.md, pica-toolkit/tests/snapshot.rs
- [Preview](https://github.com/deutsche-nationalbibliothek/pica-rs/blob/add-filter-docs/docs/book/src/referenz/kommandos/filter.md)
- [Review](https://github.com/deutsche-nationalbibliothek/pica-rs/pull/675/files#diff-106e0c0e5ed199fbb14a2226e2cfab797d34aabec4df95cbd043dd4cc31a64ad)
=> Add `filter` documentation

CHANGELOG.md, pica-path/src/lib.rs, pica-path/tests/path.rs, pica-toolkit/tests/snapshot/frequency/023-frequency-subfield-matcher.toml, pica-toolkit/tests/snapshot/frequency/024-frequency-subfield-matcher-ci.toml, pica-toolkit/tests/snapshot/frequency/586-frequency-translit-path1.toml, pica-toolkit/tests/snapshot/frequency/586-frequency-translit-path2.toml, pica-toolkit/tests/snapshot/select/586-select-translit-selector1.toml, pica-toolkit/tests/snapshot/select/586-select-translit-selector2.toml, pica-toolkit/tests/snapshot/select/605-false-positives-regex.toml
This PR removes the deprecated path syntax; please use the "set-builder" notation
```shell
$ pica select '003@.0, 044H{ 9 | b == "GND" }' DUMP.dat.gz
```
instead of
```shell
$ pica select '003@.0, 044H{ b == "GND", 9 }' DUMP.dat.gz
```
=> Remove deprecated path syntax

.github/workflows/ci.yml, .github/workflows/daily.yml, .github/workflows/release.yml, Makefile, docs/book/src/anleitungen/installation.md
This PR fixes GitHub deprecation warnings emitted by GitHub actions. Furthermore, the support for CentOS7 will be stopped.
=> Fix GitHub deprecation warnings

crates/pica-matcher/src/field_matcher.rs
This PR removes the support of the `$`-noation in a field-matcher expression. Instead of `'002@ $0 == "Olfo"'` use `'002@.0 == "Olfo"'`.
=> Remove `$`-notation in a field matcher expression

crates/pica-path/src/lib.rs, crates/pica-toolkit/tests/snapshot/select/048-select-subfield-wildcard.toml
This PR introduce the subfield wildcard `*` in a path expression. 
Example Record:
```console
$ pica filter --keep '046G' '003@?' record.dat | pica print
046G $a Mitwirkung bei: Deutsches Schaffen und Ringen im Ausland $b ein Quellenlesebuch für [...] $f 1916
046G $a Hg. v. Leitfaden der deutschsprachigen Presse im Ausland $f 1984
````
The following commands lump all subfields of the field `045G` together, which will be written to the second column:
```console
$ pica select '003@.0, 045G.*' record.dat
00010244X,Mitwirkung bei: Deutsches Schaffen und Ringen im Ausland
00010244X,"ein Quellenlesebuch für Jugend und Volk, für Schule und Haus"
00010244X,1916
00010244X,Hg. v. Leitfaden der deutschsprachigen Presse im Ausland
00010244X,1984
```
This can be useful in combination with the …
=> Add subfield wildcard in path expressions

crates/pica-matcher/src/subfield_matcher.rs, crates/pica-toolkit/tests/snapshot/filter/0301-filter-subfield-wildcard.stdin, crates/pica-toolkit/tests/snapshot/filter/0301-filter-subfield-wildcard.stdout, crates/pica-toolkit/tests/snapshot/filter/0301-filter-subfield-wildcard.toml
This PR introduce subfield code ranges in a matcher/filter expression. The following expression searches for the substring 'Algebra' in any subfields of the fields `041A` oder `041@`:
```console
$ pica filter '041[A@].[a-z] =? "Algebra"' algebra.dat
```
NB: Now, a path and a matcher expression use the same syntax (single code, ranges, wildcards).
=> Allow subfield code ranges in subfield matcher

crates/pica-matcher/src/common.rs, crates/pica-matcher/src/field_matcher.rs, crates/pica-matcher/src/lib.rs, crates/pica-matcher/src/subfield_matcher.rs, crates/pica-matcher/tests/subfield_matcher/mod.rs, crates/pica-toolkit/tests/snapshot/filter/0302-filter-field-all-quantifier.stdin, crates/pica-toolkit/tests/snapshot/filter/0302-filter-field-all-quantifier.toml, crates/pica-toolkit/tests/snapshot/filter/0302-filter-field-any-quantifier.stdin, crates/pica-toolkit/tests/snapshot/filter/0302-filter-field-any-quantifier.stdout, crates/pica-toolkit/tests/snapshot/filter/0302-filter-field-any-quantifier.toml, crates/pica-toolkit/tests/snapshot/filter/0302-filter-subfield-all-quantifier.stdin, crates/pica-toolkit/tests/snapshot/filter/0302-filter-subfield-all-quantifier.toml, crates/pica-toolkit/tests/snapshot/filter/0302-filter-subfield-any-quantifier.stdin, crates/pica-toolkit/tests/snapshot/filter/0302-filter-subfield-any-quantifier.stdout, crates/pica-toolkit/tests/snapshot/filter/0302-filter-subfield-any-quantifier.toml
This PR adds the existential and universal quantifier to a matcher expression. 
The universal quantifier (`∀`, `ALL`) requires that all fields (or subfields) must satisfy the given predicate. The following expressions matches only records, where **for all** fields `065R` the predicate (there exists a subfield `7` which is equal to `"Tg1"`) evaluates to `true`.
```console
$ pica filter -s 'ALL 065R.7 == "Tg1"' DUMP.dat.gz
$ pica filter -s '∀065R.7 == "Tg1"' DUMP.dat.gz
```
The universal quantifier can also be used in a subfield matcher expression:
```console
$ pica filter -s '010@{ ALL a == "ger" }' DUMP.dat.gz
$ pica filter -s '010@{ ∀a == "ger" }' DUMP.dat.gz
```
Because the universal quantifier evaluates to `true`, if the set of fields (or subfields) is empty, it might be necessary to …
=> Add existential and universal quantifier

.github/workflows/ci.yml, crates/pica-toolkit/Cargo.toml, crates/pica-toolkit/src/commands/filter.rs, crates/pica-toolkit/src/commands/select.rs, crates/pica-toolkit/src/filter_list.rs, crates/pica-toolkit/src/main.rs, crates/pica-utils/Cargo.toml, crates/pica-utils/src/lib.rs
This PR is necessarry in order to use fuzz tests. Compiling `polars-core` with the compiler flags of `cargo-fuzz` causes `rustc` to stops, because of an oom (out-of-memory) event.
=> utils: mv `FilterList` into `pica-toolkit`

crates/pica-toolkit/src/commands/explode.rs
This change fixes splitting a record on copy level when multiple, consecutive local fields are present.
Closes: #770
Signed-off-by: Nico Wagner <n.wagner@dnb.de>
=> Fix explode on copy level

crates/pica-matcher/src/common.rs, crates/pica-matcher/src/field_matcher.rs, crates/pica-matcher/src/record_matcher.rs, crates/pica-matcher/src/subfield_matcher.rs, crates/pica-matcher/tests/field_matcher/mod.rs, crates/pica-matcher/tests/subfield_matcher/mod.rs, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-field-f.stdin, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-field-f.toml, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-field-t.stdin, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-field-t.stdout, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-field-t.toml, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-subfield-f.stdin, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-subfield-f.toml, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-subfield-t.stdin, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-subfield-t.stdout, crates/pica-toolkit/tests/snapshot/filter/0790-filter-xor-subfield-t.toml
This PR adds the `XOR` (`^`) boolean connective to field- and subfield-matcher expressions. An exclusive or evaluates to `true` if both expressions differ (one is true, one is false). For more than two inputs the `XOR`-operator evaluates to `true` if the number of true inputs is odd.
The precedence of the `XOR` expression is lower than `AND` (`&&`) and higher than `OR` (`||`), that is `A ^ B && C` is equivalent to `A ^ (B && C)` and `A ^ B || C` is equivalent to `(A ^ B) || C`.
```console
$ pica filter "008A.a == 's' ^ 008A.a == 'f'" DUMP.dat -o out.dat
$ pica filter "008A.a == 's' XOR 008A.a == 'f'" DUMP.dat -o out.dat
$ pica filter "008A{a == 's' ^ a == 'f'} DUMP.dat -o out.dat
$ pica filter "008A{a == 's' XOR a == 'f'} DUMP.dat -o out.dat
```
Because it is very rare to use more than …
=> Add XOR operator

crates/pica-toolkit/src/commands/explode.rs, docs/content/docs/kommandos/explode.md, docs/content/docs/referenz/_index.md, docs/content/docs/referenz/filter.md
=> Stabilize `explode` command

crates/pica-format/src/lib.rs, crates/pica-format/src/parse.rs, crates/pica-format/tests/integration.rs
This PR adds the group modifiers `U` (uppercase), `L` (lowercase), `W` (remove white-spaces) and `T` (remove leading and trailing white-spaces). Modifiers must follow a single `?` after the opening parenthesis. It's possible to combine multiple modifiers like `(?WU ...)` which transforms the result to uppercase and remove all white-space characters.
```sh
$ pica select '003@.0, 006Y{ (?W "https://isni.org/isni/" 0) | S == "isni" }' goethe.dat
118540238,https://isni.org/isni/0000000120999104
```
=> Add group modifiers (format)

.github/workflows/ci.yml
The project documentation will be replaced by an PDF manual. It is no longer necessary to update the website.
=> Disable `docs` jobs

Cargo.toml, fuzz/Cargo.toml, src/matcher/field/parser.rs, src/matcher/subfield/parser.rs, src/parser.rs
This change reintroduces the minimum support of subfields according to the PICA Path specification. This feature must be activated explicitly with `--feature compat`.
=> Add minimum support of subfields (PICA Path)

crates/pica-cli/src/commands/frequency.rs
```
Benchmark 1: ./pica-v0.25 frequency -su -H 'gnd_id,label,count' '041A/*{ (9, a) | 9? && 7 =~ "^T[bfgpsu][1z]$" }' DUMP.dat --where '002@.0 =^ "A" && 041A/*.9?' -o freq.csv
Time (mean ± σ):     244.640 s ± 20.967 s    [User: 210.942 s, System: 18.619 s]
Range (min … max):   229.814 s … 259.465 s    2 runs
Benchmark 2: ./pica-main frequency -su -H 'gnd_id,label,count' '041A/*{ (9, a) | 9? && 7 =~ "^T[bfgpsu][1z]$" }' DUMP.dat --where '002@.0 =^ "A" && 041A/*.9?' -o freq.csv
Time (mean ± σ):     212.046 s ±  1.081 s    [User: 192.311 s, System: 18.450 s]
Range (min … max):   211.281 s … 212.810 s    2 runs
Summary
'./pica-main frequency -su -H 'gnd_id,label,count' '041A/*{ (9, a) | 9? && 7 =~ "^T[bfgpsu][1z]$" }' DUMP.dat --where '002@.0 =^ "A" && 041A/*.9?' -o freq.csv' ran
1.15 ± 0.10 …
```
=> perf(frequency): Use byte records instead of string records

crates/pica-cli/src/commands/select.rs
```
Benchmark 1: ./pica-v0.25 select -s -H 'ppn,gnd_id,label' '003@.0,041A/*{ (9, a) | 9? && 7 =~ "^T[bfgpsu][1z]$" }' DUMP.dat --where '002@.0 =^ "O" && 041A/*.9?' -o out.csv
Time (mean ± σ):     261.160 s ±  2.054 s    [User: 240.933 s, System: 18.878 s]
Range (min … max):   259.707 s … 262.612 s    2 runs
Benchmark 2: ./pica-main select -s -H 'ppn,gnd_id,label' '003@.0,041A/*{ (9, a) | 9? && 7 =~ "^T[bfgpsu][1z]$" }' DUMP.dat --where '002@.0 =^ "O" && 041A/*.9?' -o out.csv
Time (mean ± σ):     243.547 s ±  1.746 s    [User: 223.634 s, System: 18.478 s]
Range (min … max):   242.312 s … 244.782 s    2 runs
Summary
'./pica-main select -s -H 'ppn,gnd_id,label' '003@.0,041A/*{ (9, a) | 9? && 7 =~ "^T[bfgpsu][1z]$" }' DUMP.dat --where '002@.0 =^ "O" && 041A/*.9?' -o out.csv' ran
1.07 ± 0.01 …
```
=> perf(select): Use byte records instead of string records

crates/pica-cli/src/utils.rs, crates/pica-cli/tests/filter/mod.rs
Until now, empty allow-lists were treated in such a way that all data records were allowed. Since this can lead to subsequent errors if an error occurs when the list is created, the logic is changed in this case. From now on, all data records will be rejected if the given allow- result in an empty set.
CC: @san-uh
=> fix: handling of empty allow-lists

crates/pica-cli/src/commands/concat.rs, crates/pica-cli/src/commands/filter.rs, crates/pica-cli/src/commands/frequency.rs, crates/pica-cli/src/commands/hash.rs, crates/pica-cli/src/commands/select.rs, crates/pica-cli/tests/filter/mod.rs, src/path.rs
=> fix: process of records without a ppn

crates/pica-cli/src/commands/sample.rs, crates/pica-cli/tests/sample/mod.rs, docs/book/commands/sample.qmd
This PR adds the `--where`, `--or`, and `--not` options to the `sample` command. Now, the following two commands are equivalent:
```
$ pica filter '002@.0 =^ "Tp" && 003@.0 == "118540238"' DUMP.dat.gz | \
pica sample 23 -o samples.dat
$ pica sample 23 DUMP.dat.gz -o samples.dat \
--where '002@.0 =^ "Tp"' --and '003@.0 == "118540238"'
```
=> feat(sample): provide filter options

crates/pica-cli/tests/select/format.rs, crates/pica-cli/tests/select/mod.rs, src/error.rs, src/lib.rs, src/prelude.rs, src/query.rs
```console
$ pica select '003@{ "https://explore.gnd.network/gnd/" 0 }, 028A{a <$> (", " d <*> " " c) }' goethe.dat ada.dat
https://explore.gnd.network/gnd/118540238,Goethe, Johann Wolfgang von
https://explore.gnd.network/gnd/119232022,Lovelace, Ada King of
```
=> feat: stabilize format strings
